// <auto-generated />
using System;
using Beekeeping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beekeeping.Data.Migrations
{
    [DbContext(typeof(BeekeepingDbContext))]
    [Migration("20230802174517_SeedUserForAdministrator")]
    partial class SeedUserForAdministrator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Beekeeping.Data.Models.Apiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("NumberOfHives")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Apiaries");

                    b.HasData(
                        new
                        {
                            Id = 9150,
                            Latitude = 43.346221999999997,
                            Location = "Село Климентово, Варна",
                            Longitude = 27.946314999999998,
                            Name = "Климентово",
                            NumberOfHives = 0,
                            OwnerId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            RegistrationNumber = "9150-0015"
                        },
                        new
                        {
                            Id = 9156,
                            Latitude = 43.330429000000002,
                            Location = "Село Зорница, Варна",
                            Longitude = 27.734943999999999,
                            Name = "Зорница",
                            NumberOfHives = 0,
                            OwnerId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            RegistrationNumber = "9156-0017"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d23c4f40-0178-4622-b307-b482a79aa316"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77cc69d2-6987-43e7-a3d4-94efd0a34d2a",
                            Email = "testAdmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "TESTADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGBBPUCNgj9s2+rONpqX8QENnkMcPogdCr1pE1EdWOeRMRyLnw6Hl/qHedr2gfkI5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12F0B38F71BEA342B8A18608A5217CF6",
                            TwoFactorEnabled = false,
                            UserName = "testAdmin@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("44c36b39-ad0a-4260-b448-45bb03158888"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95274b41-99f2-48dd-85af-a3800c1dbe3c",
                            Email = "demouser@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "DEMOUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBPobu9f5OdgzHI2ex+l3yRKVDJ8k4zNzQ4XFSRmlrpVOk7mZC+RlbQzafAMxYge9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "FCB9E6CC2B6DA749BE2C0B538112615A",
                            TwoFactorEnabled = false,
                            UserName = "demouser@gmail.com"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.BeeColony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalComмent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApiaryId")
                        .HasColumnType("int");

                    b.Property<int>("BeeQueenId")
                        .HasColumnType("int");

                    b.Property<bool>("MatedBeeQueen")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfAdditionalBoxes")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfSupers")
                        .HasColumnType("int");

                    b.Property<string>("OwnerOfTheApiary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SecondBroodBox")
                        .HasColumnType("bit");

                    b.Property<bool>("Super")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfBroodBox")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("BeeQueenId")
                        .IsUnique();

                    b.ToTable("BeeColonies");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            AdditionalComмent = "Основно семейство",
                            ApiaryId = 9150,
                            BeeQueenId = 10001,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 1,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4447",
                            SecondBroodBox = true,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10002,
                            AdditionalComмent = "Основно семейство",
                            ApiaryId = 9150,
                            BeeQueenId = 10002,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4448",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10003,
                            AdditionalComмent = "Отводка",
                            ApiaryId = 9150,
                            BeeQueenId = 10003,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 0,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4449",
                            SecondBroodBox = false,
                            Super = false,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10004,
                            AdditionalComмent = "Основно семейство",
                            ApiaryId = 9150,
                            BeeQueenId = 10004,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4450",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10005,
                            AdditionalComмent = "Основно семейство",
                            ApiaryId = 9150,
                            BeeQueenId = 10005,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4451",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10006,
                            AdditionalComмent = "Отводка",
                            ApiaryId = 9150,
                            BeeQueenId = 10006,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4452",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10007,
                            AdditionalComмent = "Отводка",
                            ApiaryId = 9156,
                            BeeQueenId = 10007,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4453",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10008,
                            AdditionalComмent = "Отводка",
                            ApiaryId = 9156,
                            BeeQueenId = 10008,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4454",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        },
                        new
                        {
                            Id = 10009,
                            AdditionalComмent = "Отводка",
                            ApiaryId = 9156,
                            BeeQueenId = 10009,
                            MatedBeeQueen = true,
                            NumberOfAdditionalBoxes = 0,
                            NumberOfSupers = 1,
                            OwnerOfTheApiary = "44C36B39-AD0A-4260-B448-45BB03158888",
                            PlateNumber = "100-4455",
                            SecondBroodBox = false,
                            Super = true,
                            TypeOfBroodBox = "Многокорпусен"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.BeeQueen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BeeQueenType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BeeQueenYearOfBirth")
                        .HasColumnType("int");

                    b.Property<string>("Breeder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BeeQueens");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            BeeQueenType = "Карника",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10002,
                            BeeQueenType = "Карника",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10003,
                            BeeQueenType = "Неизвестна",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Роева"
                        },
                        new
                        {
                            Id = 10004,
                            BeeQueenType = "Карника",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10005,
                            BeeQueenType = "БМП",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10006,
                            BeeQueenType = "БМП",
                            BeeQueenYearOfBirth = 2022,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10007,
                            BeeQueenType = "Карника",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Собствено производство"
                        },
                        new
                        {
                            Id = 10008,
                            BeeQueenType = "Неизвестна",
                            BeeQueenYearOfBirth = 2023,
                            Breeder = "Роева"
                        },
                        new
                        {
                            Id = 10009,
                            BeeQueenType = "Карника",
                            BeeQueenYearOfBirth = 2022,
                            Breeder = "Собствено производство"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("CostValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DayOfTheCost")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeOfCost")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = 50001,
                            CostValue = 100m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Третиране"
                        },
                        new
                        {
                            Id = 50002,
                            CostValue = 120m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Хранене"
                        },
                        new
                        {
                            Id = 50003,
                            CostValue = 40m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Третиране"
                        },
                        new
                        {
                            Id = 50004,
                            CostValue = 80m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Хранене"
                        },
                        new
                        {
                            Id = 50005,
                            CostValue = 100m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Третиране"
                        },
                        new
                        {
                            Id = 50006,
                            CostValue = 120m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Хранене"
                        },
                        new
                        {
                            Id = 50007,
                            CostValue = 40m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Третиране"
                        },
                        new
                        {
                            Id = 50008,
                            CostValue = 200m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Транспорт"
                        },
                        new
                        {
                            Id = 50009,
                            CostValue = 150m,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheCost = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfCost = "Пчеларски инвентар"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.HiveFeeding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DayOfFeeding")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedingType")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("NumberOfBeeHives")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceOfFeeding")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HiveFeeding");

                    b.HasData(
                        new
                        {
                            Id = 30001,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfFeeding = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedingType = "Сироп",
                            NumberOfBeeHives = 10,
                            PriceOfFeeding = 80m
                        },
                        new
                        {
                            Id = 30002,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfFeeding = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedingType = "Питка",
                            NumberOfBeeHives = 10,
                            PriceOfFeeding = 120m
                        },
                        new
                        {
                            Id = 30003,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfFeeding = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedingType = "Сироп",
                            NumberOfBeeHives = 10,
                            PriceOfFeeding = 80m
                        },
                        new
                        {
                            Id = 30004,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfFeeding = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeedingType = "Питка",
                            NumberOfBeeHives = 10,
                            PriceOfFeeding = 120m
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.HiveTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActiveIngredient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfTreatedColonies")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceOfTheTreatment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResultAndCommentAboutTheTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HiveTreatments");

                    b.HasData(
                        new
                        {
                            Id = 40001,
                            ActiveIngredient = "Амитраз",
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            MedicationName = "Апивар",
                            NumberOfTreatedColonies = 10,
                            PriceOfTheTreatment = 100m,
                            ResultAndCommentAboutTheTreatment = "Опаразитеност около 1%",
                            TreatmentDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40002,
                            ActiveIngredient = "Оксалова киселина",
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            MedicationName = "Оксалова киселина",
                            NumberOfTreatedColonies = 10,
                            PriceOfTheTreatment = 40m,
                            ResultAndCommentAboutTheTreatment = "Опаразитеност около 2%",
                            TreatmentDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40003,
                            ActiveIngredient = "Амитраз",
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            MedicationName = "Апивар",
                            NumberOfTreatedColonies = 10,
                            PriceOfTheTreatment = 100m,
                            ResultAndCommentAboutTheTreatment = "Опаразитеност около 3%",
                            TreatmentDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40004,
                            ActiveIngredient = "Оксалова киселина",
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            MedicationName = "Оксалова киселина",
                            NumberOfTreatedColonies = 10,
                            PriceOfTheTreatment = 40m,
                            ResultAndCommentAboutTheTreatment = "Опаразитеност около 4%",
                            TreatmentDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DayOfTheIncome")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncomeValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeOfIncome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Incomes");

                    b.HasData(
                        new
                        {
                            Id = 60001,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 950m,
                            TypeOfIncome = "Продаден прашец"
                        },
                        new
                        {
                            Id = 60002,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 120m,
                            TypeOfIncome = "Продаден мед"
                        },
                        new
                        {
                            Id = 60003,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 250m,
                            TypeOfIncome = "Продаден мед"
                        },
                        new
                        {
                            Id = 60004,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 240m,
                            TypeOfIncome = "Продаден прашец"
                        },
                        new
                        {
                            Id = 60005,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 110m,
                            TypeOfIncome = "Продаден прополис"
                        },
                        new
                        {
                            Id = 60006,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 1350m,
                            TypeOfIncome = "Продаден мед"
                        },
                        new
                        {
                            Id = 60007,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DayOfTheIncome = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncomeValue = 290m,
                            TypeOfIncome = "Продаден мед"
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BeeColonyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DayOfInspection")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<int?>("NumberOfBroodFrames")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfFrames")
                        .HasColumnType("int");

                    b.Property<int>("Strenght")
                        .HasColumnType("int");

                    b.Property<int>("Temperament")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeeColonyId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 100000,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100001,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100002,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100003,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100004,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100005,
                            BeeColonyId = 10001,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100006,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100007,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100008,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100009,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100010,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100011,
                            BeeColonyId = 10002,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100012,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100013,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100014,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100015,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100016,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100017,
                            BeeColonyId = 10003,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100018,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100019,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100020,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100021,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100022,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100023,
                            BeeColonyId = 10004,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100024,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100025,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100026,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100027,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100028,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100029,
                            BeeColonyId = 10005,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100030,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100031,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100032,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100033,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100034,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100035,
                            BeeColonyId = 10006,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100036,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100037,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100038,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100039,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100040,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100041,
                            BeeColonyId = 10007,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100042,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100043,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100044,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100045,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100046,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100047,
                            BeeColonyId = 10008,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100048,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 1,
                            NumberOfFrames = 5,
                            Strenght = 4,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100049,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 2,
                            NumberOfFrames = 6,
                            Strenght = 5,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100050,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 3,
                            NumberOfFrames = 7,
                            Strenght = 6,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100051,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 4,
                            NumberOfFrames = 8,
                            Strenght = 7,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100052,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 5,
                            NumberOfFrames = 9,
                            Strenght = 8,
                            Temperament = 8
                        },
                        new
                        {
                            Id = 100053,
                            BeeColonyId = 10009,
                            DayOfInspection = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Общ преглед",
                            NumberOfBroodFrames = 6,
                            NumberOfFrames = 10,
                            Strenght = 9,
                            Temperament = 8
                        });
                });

            modelBuilder.Entity("Beekeeping.Data.Models.NoteToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateToBeDone")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NoteToDos");

                    b.HasData(
                        new
                        {
                            Id = 20001,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DateToBeDone = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Третиране против акар",
                            Finished = false
                        },
                        new
                        {
                            Id = 20002,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DateToBeDone = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Пролетно подхранване",
                            Finished = true
                        },
                        new
                        {
                            Id = 20003,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DateToBeDone = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Поставяне на магазини",
                            Finished = true
                        },
                        new
                        {
                            Id = 20004,
                            CreatorId = "44C36B39-AD0A-4260-B448-45BB03158888",
                            DateToBeDone = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Третиране против нозематоза",
                            Finished = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Apiary", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.ApplicationUser", null)
                        .WithMany("Apiaries")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Beekeeping.Data.Models.BeeColony", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.Apiary", "Apiary")
                        .WithMany("BeeHives")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beekeeping.Data.Models.BeeQueen", "BeeQueen")
                        .WithOne("BeeColony")
                        .HasForeignKey("Beekeeping.Data.Models.BeeColony", "BeeQueenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiary");

                    b.Navigation("BeeQueen");
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Inspection", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.BeeColony", "BeeColony")
                        .WithMany("Inspections")
                        .HasForeignKey("BeeColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeeColony");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beekeeping.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Beekeeping.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beekeeping.Data.Models.Apiary", b =>
                {
                    b.Navigation("BeeHives");
                });

            modelBuilder.Entity("Beekeeping.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Apiaries");
                });

            modelBuilder.Entity("Beekeeping.Data.Models.BeeColony", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Beekeeping.Data.Models.BeeQueen", b =>
                {
                    b.Navigation("BeeColony");
                });
#pragma warning restore 612, 618
        }
    }
}
